export const GET_USER = 'GET_USER';
export const LOGIN_USER = 'LOGIN_USER';
export const CREATE_USER = 'CREATE_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const UPDATE_USER_USERNAME = 'UPDATE_USER_USERNAME';
export const UPDATE_USER_EMAIL = 'UPDATE_USER_EMAIL';

export const GET_LISTING = 'GET_LISTING';
export const HOME_LISTINGS = 'HOME_LISTINGS';
export const SEARCH_LISTINGS = 'SEARCH_LISTINGS';

export const GET_MESSAGE = 'GET_MESSAGE';
export const POST_MESSAGE = 'POST_MESSAGE';
